### ISSUE TITLE
Left mouse double click throws error

### ISSUE THREAD

**Issue by jamiedbennett** [spencerparkin/TwistyPuzzle#1]
Using the snap from the beta channel on Ubuntu 16.10 when I double click the left mouse button on the cube I get pop-up errors such as:

(TwistyPuzzle:9135): Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
./src/gtk/window.cpp(4905): assert ""g_captureWindow"" failed in DoReleaseMouse(): can't release mouse - not captured
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(TwistyPuzzle:9135): Gtk-WARNING **: gtk_window_set_titlebar() called on a realized window
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
./src/common/wincmn.cpp(3349): assert ""!wxMouseCapture::stack.empty()"" failed in ReleaseMouse(): Releasing mouse capture but capture stack empty?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by spencerparkin** [comment]
Issue should be fixed now as of commit #9d23f19235d5.  The fix will show up in the next snap release.

Thank you for submitting the bug.
